"""Add max_weight_constraint

Revision ID: 75f38282cfa1
Revises: 85890eae5c9e
Create Date: 2026-09-17 14:03:44.518873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f38282cfa1'
down_revision: Union[str, Sequence[str], None] = '85890eae5c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('max_weight_constraint', sa.Float(), nullable=False, server_default='0.40'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'max_weight_constraint')
    # ### end Alembic commands ###
